---
# tasks file for runvm
- name: Create a new EC2 key
  amazon.aws.ec2_key:
    name: ec2conveer
    state: present
  register: ec2_key_result

- name: Save private key
  copy: content="{{ ec2_key_result.key.private_key }}" dest="./id_rsa" mode=0600
  when: ec2_key_result.changed

- name: Create security group
  amazon.aws.ec2_group:
    description: grant all to servers
    name: security_group
    state: present
    rules:
      - proto: all
        cidr_ip: 0.0.0.0/0

- name: Create EC2 instance
  amazon.aws.ec2:
    assign_public_ip: yes
    count: 2
    group: security_group
    image: ami-0f7cd40eac2214b37
    instance_type: t2.micro
    key_name: ec2conveer
    state: running
    instance_ids:
      - buildserver
      - webserver    
...