---
# tasks file for runvm
- name: Generate key
  
- name: Ensure that aws cli installed
  community.aws.ec2_instance:
    image_id: ami-0f7cd40eac2214b37
    instance_type: "t2.micro"
    key_name: aws_key
    name: buildserver
    region: eu-west-3
    security_group: allow_all_sg
    state: present
    profile: ~/boto.config
    network:
      assign_public_ip: yes
    register: var_buildserver
...