---
# tasks file for runvm
- name: Create a new EC2 key
  amazon.aws.ec2_key:
    name: ec2conveer
    state: present
  register: ec2_key_result

- name: Save private key
  copy: content="{{ ec2_key_result.key.private_key }}" dest="/root/.ssh/id_rsa" mode=0600

- name: Create security group
  amazon.aws.ec2_group:
    description: grant all to servers
    name: securitygroup
    state: present
    rules:
      - proto: all
        cidr_ip: 0.0.0.0/0

- name: Create EC2 instance for buildserver
  amazon.aws.ec2_instance:
    name: buildserver
    image_id: ami-0f7cd40eac2214b37
    instance_type: "t2.micro"
    key_name: ec2conveer
    security_group: securitygroup
    state: running
    network:
      assign_public_ip: yes

- name: Gather instances information
  ec2_instance_info:
    filters:
      "tag:Name": buildserver
  register: ec2_node_info

- name: Adding host to inventory
  add_host:
    name: '{{ ec2_node_info.instances[0].public_ip_address }}'
    groups: build

- name: Create EC2 instance for webserver
  amazon.aws.ec2_instance:
    name: webserver
    image_id: ami-0f7cd40eac2214b37
    instance_type: "t2.micro"
    key_name: ec2conveer
    security_group: securitygroup
    state: running
    network:
      assign_public_ip: yes
  register: webserver_result

- name: Gather instances information
  ec2_instance_info:
    filters:
      "tag:Name": webserver
  register: ec2_node_info

- name: Adding host to inventory
  add_host:
    name: '{{ ec2_node_info.instances[0].public_ip_address }}'
    groups: web
...